# automatically generated by the FlatBuffers compiler, do not modify

# namespace: gamma_api

import flatbuffers

class Table(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsTable(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Table()
        x.Init(buf, n + offset)
        return x

    # Table
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Table
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Table
    def Fields(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .FieldInfo import FieldInfo
            obj = FieldInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Table
    def FieldsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Table
    def VectorsInfo(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .VectorInfo import VectorInfo
            obj = VectorInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Table
    def VectorsInfoLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Table
    def IndexType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Table
    def IndexParams(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Table
    def RefreshInterval(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 1000

    # Table
    def EnableIdCache(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Table
    def EnableRealtime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def TableStart(builder): builder.StartObject(8)
def TableAddName(builder, name): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)
def TableAddFields(builder, fields): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(fields), 0)
def TableStartFieldsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def TableAddVectorsInfo(builder, vectorsInfo): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(vectorsInfo), 0)
def TableStartVectorsInfoVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def TableAddIndexType(builder, indexType): builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(indexType), 0)
def TableAddIndexParams(builder, indexParams): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(indexParams), 0)
def TableAddRefreshInterval(builder, refreshInterval): builder.PrependInt32Slot(5, refreshInterval, 1000)
def TableAddEnableIdCache(builder, enableIdCache): builder.PrependBoolSlot(6, enableIdCache, 0)
def TableAddEnableRealtime(builder, enableRealtime): builder.PrependBoolSlot(7, enableRealtime, 0)
def TableEnd(builder): return builder.EndObject()
