// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: errors.proto

#include "errors.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

class ErrorDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Error>
      _instance;
} _Error_default_instance_;
namespace protobuf_errors_2eproto {
static void InitDefaultsError() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_Error_default_instance_;
    new (ptr) ::Error();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Error::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Error =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsError}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Error.base);
}

::google::protobuf::Metadata file_level_metadata[1];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Error, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Error, code_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Error, msg_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Error)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_Error_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "errors.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\014errors.proto\".\n\005Error\022\030\n\004code\030\001 \001(\0162\n."
      "ErrorEnum\022\013\n\003msg\030\002 \001(\t*\244\r\n\tErrorEnum\022\013\n\007"
      "SUCCESS\020\000\022\022\n\016INTERNAL_ERROR\020\001\022\021\n\rUNKNOWN"
      "_ERROR\020\002\022\031\n\025AUTHENTICATION_FAILED\020\003\022\013\n\007R"
      "ECOVER\020\004\022\013\n\007TIMEOUT\020\005\022\017\n\013PARAM_ERROR\020\006\022\020"
      "\n\014CONFIG_ERROR\020\007\022\037\n\033MASTER_PS_NOT_ENOUGH"
      "_SELECT\020d\022\027\n\023ROUTER_NO_PS_CLIENT\020x\022\032\n\026RO"
      "UTER_CALL_PS_RPC_ERR\020y\022\024\n\017PARTITION_EXIS"
      "T\020\214\001\022\030\n\023PARTITION_NOT_EXIST\020\215\001\022\031\n\024PARTIT"
      "ION_NOT_LEADER\020\216\001\022\030\n\023PARTITION_NO_LEADER"
      "\020\217\001\022\031\n\024PARTITION_IS_INVALID\020\220\001\022\030\n\023PARTIT"
      "ION_IS_CLOSED\020\221\001\022!\n\034PARTITION_RESOURCE_E"
      "XHAUSTED\020\222\001\022\037\n\032PARTITION_SERVER_NOT_EXIS"
      "T\020\240\001\022\033\n\026PARTITION_SERVER_ERROR\020\241\001\022\023\n\016USE"
      "R_NOT_EXIST\020\264\001\022\021\n\014DB_NOT_EXIST\020\310\001\022\r\n\010DB_"
      "EXIST\020\311\001\022\021\n\014DB_NOT_EMPTY\020\312\001\022\020\n\013SPACE_EXI"
      "ST\020\334\001\022\024\n\017SPACE_NOT_EXIST\020\335\001\022\024\n\017ALIAS_NOT"
      "_EXIST\020\360\001\022\020\n\013ALIAS_EXIST\020\361\001\022\027\n\022DOCUMENT_"
      "NOT_EXIST\020\204\002\022\033\n\026PRIMARY_KEY_IS_INVALID\020\205"
      "\002\022\035\n\030FILTER_OPERATOR_TYPE_ERR\020\254\002\022\'\n\"FILT"
      "ER_CONDITION_OPERATOR_TYPE_ERR\020\255\002\022\032\n\025UPS"
      "ERT_INVALID_PARAMS\020\220\003\022\037\n\032DELETE_BY_QUERY"
      "_SERACH_ERR\020\244\003\022#\n\036DELETE_BY_QUERY_SEARCH"
      "_ID_IS_0\020\245\003\0227\n2DELETE_INVALID_PARAMS_SHO"
      "ULD_NOT_HAVE_VECTOR_FIELD\020\246\003\0227\n2DELETE_I"
      "NVALID_PARAMS_BOTH_DOCUMENT_IDS_AND_VECT"
      "OR\020\247\003\022<\n7DELETE_INVALID_PARAMS_LENGTH_OF"
      "_DOCUMENT_IDS_BEYOND_500\020\250\003\022D\n\?DELETE_IN"
      "VALID_PARAMS_SHOULD_HAVE_ONE_OF_DOCUMENT"
      "_IDS_OR_FILTER\020\251\003\022\025\n\020QUERY_ENGINE_ERR\020\270\003"
      "\022;\n6QUERY_INVALID_PARAMS_LENGTH_OF_DOCUM"
      "ENT_IDS_BEYOND_500\020\271\003\022C\n>QUERY_INVALID_P"
      "ARAMS_SHOULD_HAVE_ONE_OF_DOCUMENT_IDS_OR"
      "_FILTER\020\272\003\0226\n1QUERY_INVALID_PARAMS_SHOUL"
      "D_NOT_HAVE_VECTOR_FIELD\020\273\003\0226\n1QUERY_INVA"
      "LID_PARAMS_BOTH_DOCUMENT_IDS_AND_FILTER\020"
      "\274\003\022\035\n\030QUERY_RESPONSE_PARSE_ERR\020\275\003\0223\n.SEA"
      "RCH_INVALID_PARAMS_SHOULD_HAVE_VECTOR_FI"
      "ELD\020\314\003\022\026\n\021SEARCH_ENGINE_ERR\020\315\003\022\036\n\031SEARCH"
      "_RESPONSE_PARSE_ERR\020\316\003\022 \n\033FORCE_MERGE_BU"
      "ILD_INDEX_ERR\020\364\003\022\016\n\tFLUSH_ERR\020\330\004\022\030\n\023SERV"
      "ICE_UNAVAILABLE\020\274\005\022\024\n\017RPC_PARAM_ERROR\020\275\005"
      "\022\031\n\024METHOD_NOT_IMPLEMENT\020\276\005\022\034\n\027CREATE_RP"
      "CCLIENT_FAILED\020\277\005\022\032\n\025CALL_RPCCLIENT_FAIL"
      "ED\020\300\005B\016H\001Z\n./vearchpbb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 1789);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "errors.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_errors_2eproto
const ::google::protobuf::EnumDescriptor* ErrorEnum_descriptor() {
  protobuf_errors_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_errors_2eproto::file_level_enum_descriptors[0];
}
bool ErrorEnum_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 100:
    case 120:
    case 121:
    case 140:
    case 141:
    case 142:
    case 143:
    case 144:
    case 145:
    case 146:
    case 160:
    case 161:
    case 180:
    case 200:
    case 201:
    case 202:
    case 220:
    case 221:
    case 240:
    case 241:
    case 260:
    case 261:
    case 300:
    case 301:
    case 400:
    case 420:
    case 421:
    case 422:
    case 423:
    case 424:
    case 425:
    case 440:
    case 441:
    case 442:
    case 443:
    case 444:
    case 445:
    case 460:
    case 461:
    case 462:
    case 500:
    case 600:
    case 700:
    case 701:
    case 702:
    case 703:
    case 704:
      return true;
    default:
      return false;
  }
}


// ===================================================================

void Error::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Error::kCodeFieldNumber;
const int Error::kMsgFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Error::Error()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_errors_2eproto::scc_info_Error.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Error)
}
Error::Error(const Error& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.msg().size() > 0) {
    msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.msg_);
  }
  code_ = from.code_;
  // @@protoc_insertion_point(copy_constructor:Error)
}

void Error::SharedCtor() {
  msg_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  code_ = 0;
}

Error::~Error() {
  // @@protoc_insertion_point(destructor:Error)
  SharedDtor();
}

void Error::SharedDtor() {
  msg_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Error::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Error::descriptor() {
  ::protobuf_errors_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_errors_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Error& Error::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_errors_2eproto::scc_info_Error.base);
  return *internal_default_instance();
}


void Error::Clear() {
// @@protoc_insertion_point(message_clear_start:Error)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  msg_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  code_ = 0;
  _internal_metadata_.Clear();
}

bool Error::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Error)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .ErrorEnum code = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_code(static_cast< ::ErrorEnum >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string msg = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_msg()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->msg().data(), static_cast<int>(this->msg().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Error.msg"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Error)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Error)
  return false;
#undef DO_
}

void Error::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Error)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .ErrorEnum code = 1;
  if (this->code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->code(), output);
  }

  // string msg = 2;
  if (this->msg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->msg().data(), static_cast<int>(this->msg().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Error.msg");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->msg(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Error)
}

::google::protobuf::uint8* Error::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Error)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .ErrorEnum code = 1;
  if (this->code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->code(), target);
  }

  // string msg = 2;
  if (this->msg().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->msg().data(), static_cast<int>(this->msg().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Error.msg");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->msg(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Error)
  return target;
}

size_t Error::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Error)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string msg = 2;
  if (this->msg().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->msg());
  }

  // .ErrorEnum code = 1;
  if (this->code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->code());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Error::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Error)
  GOOGLE_DCHECK_NE(&from, this);
  const Error* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Error>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Error)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Error)
    MergeFrom(*source);
  }
}

void Error::MergeFrom(const Error& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Error)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.msg().size() > 0) {

    msg_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.msg_);
  }
  if (from.code() != 0) {
    set_code(from.code());
  }
}

void Error::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Error)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Error::CopyFrom(const Error& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Error)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Error::IsInitialized() const {
  return true;
}

void Error::Swap(Error* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Error::InternalSwap(Error* other) {
  using std::swap;
  msg_.Swap(&other->msg_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(code_, other->code_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Error::GetMetadata() const {
  protobuf_errors_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_errors_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Error* Arena::CreateMaybeMessage< ::Error >(Arena* arena) {
  return Arena::CreateInternal< ::Error >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
