// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: errors.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_errors_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_errors_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_errors_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_errors_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_errors_2eproto;
namespace vearchpb {
class Error;
struct ErrorDefaultTypeInternal;
extern ErrorDefaultTypeInternal _Error_default_instance_;
}  // namespace vearchpb
PROTOBUF_NAMESPACE_OPEN
template<> ::vearchpb::Error* Arena::CreateMaybeMessage<::vearchpb::Error>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace vearchpb {

enum ErrorEnum : int {
  SUCCESS = 0,
  INTERNAL_ERROR = 1,
  UNKNOWN_ERROR = 2,
  AUTHENTICATION_FAILED = 3,
  RECOVER = 4,
  TIMEOUT = 5,
  PARAM_ERROR = 6,
  CONFIG_ERROR = 7,
  MASTER_PS_NOT_ENOUGH_SELECT = 100,
  ROUTER_NO_PS_CLIENT = 120,
  ROUTER_CALL_PS_RPC_ERR = 121,
  PARTITION_EXIST = 140,
  PARTITION_NOT_EXIST = 141,
  PARTITION_NOT_LEADER = 142,
  PARTITION_NO_LEADER = 143,
  PARTITION_IS_INVALID = 144,
  PARTITION_IS_CLOSED = 145,
  PARTITION_RESOURCE_EXHAUSTED = 146,
  PARTITION_SERVER_NOT_EXIST = 160,
  PARTITION_SERVER_ERROR = 161,
  USER_NOT_EXIST = 180,
  USER_EXIST = 181,
  ROLE_NOT_EXIST = 190,
  ROLE_EXIST = 191,
  DB_NOT_EXIST = 200,
  DB_EXIST = 201,
  DB_NOT_EMPTY = 202,
  SPACE_EXIST = 220,
  SPACE_NOT_EXIST = 221,
  ALIAS_NOT_EXIST = 240,
  ALIAS_EXIST = 241,
  DOCUMENT_NOT_EXIST = 260,
  PRIMARY_KEY_IS_INVALID = 261,
  FILTER_OPERATOR_TYPE_ERR = 300,
  FILTER_CONDITION_OPERATOR_TYPE_ERR = 301,
  UPSERT_INVALID_PARAMS = 400,
  DELETE_BY_QUERY_SERACH_ERR = 420,
  DELETE_BY_QUERY_SEARCH_ID_IS_0 = 421,
  DELETE_INVALID_PARAMS_SHOULD_NOT_HAVE_VECTOR_FIELD = 422,
  DELETE_INVALID_PARAMS_BOTH_DOCUMENT_IDS_AND_VECTOR = 423,
  DELETE_INVALID_PARAMS_LENGTH_OF_DOCUMENT_IDS_BEYOND_500 = 424,
  DELETE_INVALID_PARAMS_SHOULD_HAVE_ONE_OF_DOCUMENT_IDS_OR_FILTER = 425,
  QUERY_ENGINE_ERR = 440,
  QUERY_INVALID_PARAMS_LENGTH_OF_DOCUMENT_IDS_BEYOND_500 = 441,
  QUERY_INVALID_PARAMS_SHOULD_HAVE_ONE_OF_DOCUMENT_IDS_OR_FILTER = 442,
  QUERY_INVALID_PARAMS_SHOULD_NOT_HAVE_VECTOR_FIELD = 443,
  QUERY_INVALID_PARAMS_BOTH_DOCUMENT_IDS_AND_FILTER = 444,
  QUERY_RESPONSE_PARSE_ERR = 445,
  SEARCH_INVALID_PARAMS_SHOULD_HAVE_VECTOR_FIELD = 460,
  SEARCH_ENGINE_ERR = 461,
  SEARCH_RESPONSE_PARSE_ERR = 462,
  FORCE_MERGE_BUILD_INDEX_ERR = 500,
  FLUSH_ERR = 600,
  SERVICE_UNAVAILABLE = 700,
  RPC_PARAM_ERROR = 701,
  METHOD_NOT_IMPLEMENT = 702,
  CREATE_RPCCLIENT_FAILED = 703,
  CALL_RPCCLIENT_FAILED = 704,
  ErrorEnum_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  ErrorEnum_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool ErrorEnum_IsValid(int value);
constexpr ErrorEnum ErrorEnum_MIN = SUCCESS;
constexpr ErrorEnum ErrorEnum_MAX = CALL_RPCCLIENT_FAILED;
constexpr int ErrorEnum_ARRAYSIZE = ErrorEnum_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* ErrorEnum_descriptor();
template<typename T>
inline const std::string& ErrorEnum_Name(T enum_t_value) {
  static_assert(::std::is_same<T, ErrorEnum>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function ErrorEnum_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    ErrorEnum_descriptor(), enum_t_value);
}
inline bool ErrorEnum_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, ErrorEnum* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<ErrorEnum>(
    ErrorEnum_descriptor(), name, value);
}
// ===================================================================

class Error final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:vearchpb.Error) */ {
 public:
  inline Error() : Error(nullptr) {}
  ~Error() override;
  explicit PROTOBUF_CONSTEXPR Error(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Error(const Error& from);
  Error(Error&& from) noexcept
    : Error() {
    *this = ::std::move(from);
  }

  inline Error& operator=(const Error& from) {
    CopyFrom(from);
    return *this;
  }
  inline Error& operator=(Error&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Error& default_instance() {
    return *internal_default_instance();
  }
  static inline const Error* internal_default_instance() {
    return reinterpret_cast<const Error*>(
               &_Error_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Error& a, Error& b) {
    a.Swap(&b);
  }
  inline void Swap(Error* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Error* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Error* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Error>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Error& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Error& from) {
    Error::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Error* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "vearchpb.Error";
  }
  protected:
  explicit Error(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgFieldNumber = 2,
    kCodeFieldNumber = 1,
  };
  // string msg = 2;
  void clear_msg();
  const std::string& msg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_msg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_msg();
  PROTOBUF_NODISCARD std::string* release_msg();
  void set_allocated_msg(std::string* msg);
  private:
  const std::string& _internal_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_msg(const std::string& value);
  std::string* _internal_mutable_msg();
  public:

  // .vearchpb.ErrorEnum code = 1;
  void clear_code();
  ::vearchpb::ErrorEnum code() const;
  void set_code(::vearchpb::ErrorEnum value);
  private:
  ::vearchpb::ErrorEnum _internal_code() const;
  void _internal_set_code(::vearchpb::ErrorEnum value);
  public:

  // @@protoc_insertion_point(class_scope:vearchpb.Error)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_;
    int code_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_errors_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Error

// .vearchpb.ErrorEnum code = 1;
inline void Error::clear_code() {
  _impl_.code_ = 0;
}
inline ::vearchpb::ErrorEnum Error::_internal_code() const {
  return static_cast< ::vearchpb::ErrorEnum >(_impl_.code_);
}
inline ::vearchpb::ErrorEnum Error::code() const {
  // @@protoc_insertion_point(field_get:vearchpb.Error.code)
  return _internal_code();
}
inline void Error::_internal_set_code(::vearchpb::ErrorEnum value) {
  
  _impl_.code_ = value;
}
inline void Error::set_code(::vearchpb::ErrorEnum value) {
  _internal_set_code(value);
  // @@protoc_insertion_point(field_set:vearchpb.Error.code)
}

// string msg = 2;
inline void Error::clear_msg() {
  _impl_.msg_.ClearToEmpty();
}
inline const std::string& Error::msg() const {
  // @@protoc_insertion_point(field_get:vearchpb.Error.msg)
  return _internal_msg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Error::set_msg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.msg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:vearchpb.Error.msg)
}
inline std::string* Error::mutable_msg() {
  std::string* _s = _internal_mutable_msg();
  // @@protoc_insertion_point(field_mutable:vearchpb.Error.msg)
  return _s;
}
inline const std::string& Error::_internal_msg() const {
  return _impl_.msg_.Get();
}
inline void Error::_internal_set_msg(const std::string& value) {
  
  _impl_.msg_.Set(value, GetArenaForAllocation());
}
inline std::string* Error::_internal_mutable_msg() {
  
  return _impl_.msg_.Mutable(GetArenaForAllocation());
}
inline std::string* Error::release_msg() {
  // @@protoc_insertion_point(field_release:vearchpb.Error.msg)
  return _impl_.msg_.Release();
}
inline void Error::set_allocated_msg(std::string* msg) {
  if (msg != nullptr) {
    
  } else {
    
  }
  _impl_.msg_.SetAllocated(msg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.msg_.IsDefault()) {
    _impl_.msg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:vearchpb.Error.msg)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace vearchpb

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::vearchpb::ErrorEnum> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::vearchpb::ErrorEnum>() {
  return ::vearchpb::ErrorEnum_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_errors_2eproto
