// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snapshot.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_snapshot_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_snapshot_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_snapshot_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_snapshot_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_snapshot_2eproto;
namespace vearchpb {
class SnapshotMsg;
struct SnapshotMsgDefaultTypeInternal;
extern SnapshotMsgDefaultTypeInternal _SnapshotMsg_default_instance_;
}  // namespace vearchpb
PROTOBUF_NAMESPACE_OPEN
template<> ::vearchpb::SnapshotMsg* Arena::CreateMaybeMessage<::vearchpb::SnapshotMsg>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace vearchpb {

enum SnapshotStatus : int {
  UnUse = 0,
  Start = 1,
  Running = 2,
  Finish = 3,
  SnapshotStatus_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::min(),
  SnapshotStatus_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<int32_t>::max()
};
bool SnapshotStatus_IsValid(int value);
constexpr SnapshotStatus SnapshotStatus_MIN = UnUse;
constexpr SnapshotStatus SnapshotStatus_MAX = Finish;
constexpr int SnapshotStatus_ARRAYSIZE = SnapshotStatus_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SnapshotStatus_descriptor();
template<typename T>
inline const std::string& SnapshotStatus_Name(T enum_t_value) {
  static_assert(::std::is_same<T, SnapshotStatus>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function SnapshotStatus_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    SnapshotStatus_descriptor(), enum_t_value);
}
inline bool SnapshotStatus_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, SnapshotStatus* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<SnapshotStatus>(
    SnapshotStatus_descriptor(), name, value);
}
// ===================================================================

class SnapshotMsg final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:vearchpb.SnapshotMsg) */ {
 public:
  inline SnapshotMsg() : SnapshotMsg(nullptr) {}
  ~SnapshotMsg() override;
  explicit PROTOBUF_CONSTEXPR SnapshotMsg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SnapshotMsg(const SnapshotMsg& from);
  SnapshotMsg(SnapshotMsg&& from) noexcept
    : SnapshotMsg() {
    *this = ::std::move(from);
  }

  inline SnapshotMsg& operator=(const SnapshotMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline SnapshotMsg& operator=(SnapshotMsg&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SnapshotMsg& default_instance() {
    return *internal_default_instance();
  }
  static inline const SnapshotMsg* internal_default_instance() {
    return reinterpret_cast<const SnapshotMsg*>(
               &_SnapshotMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SnapshotMsg& a, SnapshotMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(SnapshotMsg* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SnapshotMsg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SnapshotMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SnapshotMsg>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SnapshotMsg& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SnapshotMsg& from) {
    SnapshotMsg::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SnapshotMsg* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "vearchpb.SnapshotMsg";
  }
  protected:
  explicit SnapshotMsg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFileNameFieldNumber = 1,
    kDataFieldNumber = 2,
    kStatusFieldNumber = 3,
  };
  // string file_name = 1;
  void clear_file_name();
  const std::string& file_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_file_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_file_name();
  PROTOBUF_NODISCARD std::string* release_file_name();
  void set_allocated_file_name(std::string* file_name);
  private:
  const std::string& _internal_file_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_file_name(const std::string& value);
  std::string* _internal_mutable_file_name();
  public:

  // bytes data = 2;
  void clear_data();
  const std::string& data() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_data(ArgT0&& arg0, ArgT... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* data);
  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // .vearchpb.SnapshotStatus status = 3;
  void clear_status();
  ::vearchpb::SnapshotStatus status() const;
  void set_status(::vearchpb::SnapshotStatus value);
  private:
  ::vearchpb::SnapshotStatus _internal_status() const;
  void _internal_set_status(::vearchpb::SnapshotStatus value);
  public:

  // @@protoc_insertion_point(class_scope:vearchpb.SnapshotMsg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr file_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
    int status_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_snapshot_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SnapshotMsg

// string file_name = 1;
inline void SnapshotMsg::clear_file_name() {
  _impl_.file_name_.ClearToEmpty();
}
inline const std::string& SnapshotMsg::file_name() const {
  // @@protoc_insertion_point(field_get:vearchpb.SnapshotMsg.file_name)
  return _internal_file_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SnapshotMsg::set_file_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.file_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:vearchpb.SnapshotMsg.file_name)
}
inline std::string* SnapshotMsg::mutable_file_name() {
  std::string* _s = _internal_mutable_file_name();
  // @@protoc_insertion_point(field_mutable:vearchpb.SnapshotMsg.file_name)
  return _s;
}
inline const std::string& SnapshotMsg::_internal_file_name() const {
  return _impl_.file_name_.Get();
}
inline void SnapshotMsg::_internal_set_file_name(const std::string& value) {
  
  _impl_.file_name_.Set(value, GetArenaForAllocation());
}
inline std::string* SnapshotMsg::_internal_mutable_file_name() {
  
  return _impl_.file_name_.Mutable(GetArenaForAllocation());
}
inline std::string* SnapshotMsg::release_file_name() {
  // @@protoc_insertion_point(field_release:vearchpb.SnapshotMsg.file_name)
  return _impl_.file_name_.Release();
}
inline void SnapshotMsg::set_allocated_file_name(std::string* file_name) {
  if (file_name != nullptr) {
    
  } else {
    
  }
  _impl_.file_name_.SetAllocated(file_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.file_name_.IsDefault()) {
    _impl_.file_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:vearchpb.SnapshotMsg.file_name)
}

// bytes data = 2;
inline void SnapshotMsg::clear_data() {
  _impl_.data_.ClearToEmpty();
}
inline const std::string& SnapshotMsg::data() const {
  // @@protoc_insertion_point(field_get:vearchpb.SnapshotMsg.data)
  return _internal_data();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SnapshotMsg::set_data(ArgT0&& arg0, ArgT... args) {
 
 _impl_.data_.SetBytes(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:vearchpb.SnapshotMsg.data)
}
inline std::string* SnapshotMsg::mutable_data() {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:vearchpb.SnapshotMsg.data)
  return _s;
}
inline const std::string& SnapshotMsg::_internal_data() const {
  return _impl_.data_.Get();
}
inline void SnapshotMsg::_internal_set_data(const std::string& value) {
  
  _impl_.data_.Set(value, GetArenaForAllocation());
}
inline std::string* SnapshotMsg::_internal_mutable_data() {
  
  return _impl_.data_.Mutable(GetArenaForAllocation());
}
inline std::string* SnapshotMsg::release_data() {
  // @@protoc_insertion_point(field_release:vearchpb.SnapshotMsg.data)
  return _impl_.data_.Release();
}
inline void SnapshotMsg::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  _impl_.data_.SetAllocated(data, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:vearchpb.SnapshotMsg.data)
}

// .vearchpb.SnapshotStatus status = 3;
inline void SnapshotMsg::clear_status() {
  _impl_.status_ = 0;
}
inline ::vearchpb::SnapshotStatus SnapshotMsg::_internal_status() const {
  return static_cast< ::vearchpb::SnapshotStatus >(_impl_.status_);
}
inline ::vearchpb::SnapshotStatus SnapshotMsg::status() const {
  // @@protoc_insertion_point(field_get:vearchpb.SnapshotMsg.status)
  return _internal_status();
}
inline void SnapshotMsg::_internal_set_status(::vearchpb::SnapshotStatus value) {
  
  _impl_.status_ = value;
}
inline void SnapshotMsg::set_status(::vearchpb::SnapshotStatus value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:vearchpb.SnapshotMsg.status)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace vearchpb

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::vearchpb::SnapshotStatus> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::vearchpb::SnapshotStatus>() {
  return ::vearchpb::SnapshotStatus_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_snapshot_2eproto
