LIST_DATABASE_URI = "/dbs"
DATABASE_URI = "/dbs/%(database_name)s"  # create or delete database use this uri
LIST_SPACE_URI = "/dbs/%(database_name)s/spaces"
SPACE_URI = "/dbs/%(database_name)s/spaces/%(space_name)s"
UPSERT_DOC_URI = "/documents/upsert"
DELETE_DOC_URI = "/documents/delete"
SEARCH_DOC_URI = "/documents/search"
QUERY_DOC_URI = "/documents/query"
INDEX_URI = "/documents/index"
