/*
Vearch Database API

Testing DatabaseAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package vearch_client

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/vearch/vearch/sdk/go"
)

func Test_vearch_client_DatabaseAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test DatabaseAPIService CreateDatabase", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		httpRes, err := apiClient.DatabaseAPI.CreateDatabase(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DatabaseAPIService DeleteDB", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var dBNAME string

		httpRes, err := apiClient.DatabaseAPI.DeleteDB(context.Background(), dBNAME).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
